spring:
  application:
    name: ${SPRING_APP_NAME:springsecurity}
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/${DATABASE_NAME:securitylab}?sslmode=${DATABASE_SSLMODE:disable}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}

  jpa:
      show-sql: ${JPA_SHOW_SQL:false}

  flyway:
    enabled: true
    locations: classpath:db/migration
#  security:
#    user:
#      name: ${SECURITY_USERNAME:admin}
#      password: ${SECURITY_PASSWORD:admin}

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
      flywaydb: DEBUG